import { Chapter } from "../types";

export const ch00_overview: Chapter = {
  id: 0,
  slug: "welcome-and-big-picture",
  title: "Welcome & The Big Picture",
  subtitle: "From a two-line lyric to a 48 kHz stereo song",
  pipelineStage: "overview",
  estMinutes: 5,
  hook: "A computer was given two lines of lyrics and 71 seconds later produced a full song with singing and acoustic guitar. How is that possible?",
  analogy: {
    title: "The Multidisciplinary Music Studio",
    body: "Imagine a master recording studio with four specialized human departments. Department 1 is a songwriter who jots down lead sheet chords on paper. Department 2 is a session vocalist singing a rough scratch track to lock in the groove and syllables. Department 3 is a sound designer who shapes textured instrument timbres out of raw synthesizer static. Department 4 is the audio mastering engineer who converts those magnetic tracks into crystal-clear stereo audio. YuE2-3B houses all four departments inside one single neural network.",
    breaksDown: "In a human studio, the musicians have feelings, artistic intent, and conscious listening. In YuE2-3B, there is zero intent or consciousness—every single stage is mathematical probability, predicting the most statistically plausible next numbers based on billions of training patterns."
  },
  concept: [
    {
      heading: "No Human Played This",
      content: "When you listen to the songs generated by YuE2-3B (like the official demo tracks below), you hear a human-sounding singing voice with vibrato, nuanced acoustic guitar strumming, and crisp drum fills. Yet not a single acoustic microphone was used. Every sound you hear was calculated by a machine learning model.",
      eli5Content: "A computer made this whole song from scratch just from reading lyrics. It didn't record real instruments—it calculated every sound wave as numbers!"
    },
    {
      heading: "The Four-Stage Assembly Line",
      content: "Music is enormously complex: one second of stereo audio contains 96,000 numbers. Generating that directly from words in one giant leap produces noisy mush. YuE2-3B succeeds because it breaks music generation into four progressive stages:\n\n1. Symbolic Plan: Writes sheet music (melody and chords in ABC notation).\n2. Semantic Rough Draft: Generates low-speed tokens that capture vocal timing and rhythm.\n3. Acoustic Latents: Uses flow matching to sculpt rich sound textures out of random noise.\n4. VAE Decoder: Unpacks those compressed textures into a 48 kHz stereo sound wave.",
      eli5Content: "Instead of jumping straight from words to sound, the AI makes a musical sketch first, then adds instruments, then sharpens the sound—just like drawing a cartoon sketch before painting final colors."
    },
    {
      heading: "What You Need to Know to Understand This",
      content: "You do not need a degree in linear algebra, calculus, or deep learning. If you know what a Python list, dictionary, for-loop, and random number generator are, you have everything needed to understand the mechanics inside this 3-billion-parameter model.",
      eli5Content: "If you can write basic Python code with lists and loops, you can understand how this music AI works!"
    }
  ],
  inYuE2: {
    summary: "YuE2-3B is an open-weights model developed by M-A-P. It runs locally on a 24 GB NVIDIA GPU, creating full stereo songs in about 71 seconds.",
    factIds: ["developer", "task", "audio_output", "parameter_count", "license"]
  },
  pythonCorner: [
    {
      title: "The Entire YuE2 Generation in 6 Lines of Python",
      language: "python",
      type: "needs-gpu",
      description: "This is the real, unmodified Python call provided by M-A-P to run YuE2 on an NVIDIA GPU.",
      code: `# Requires: Linux, 24GB NVIDIA GPU, pip install yue2_infer-0.1.5
from yue2 import YuE2Pipeline

pipe = YuE2Pipeline.from_pretrained("m-a-p/YuE2-3B", device="cuda")

style = "Indie pop, warm female vocal, acoustic guitar, soft drums"
lyrics = """Sunlight through the kitchen glass,
Watch the quiet morning pass."""

# Run the 4-stage pipeline
song = pipe(style=style, lyrics=lyrics, cot="full", seed=1234)
song.save("morning_light.flac")`
    }
  ],
  newTerms: ["model", "parameter", "generative-ai", "cc-by-nc-40"],
  recap: [
    "YuE2-3B generates complete 48 kHz stereo songs with vocals and accompaniment from text lyrics.",
    "Instead of generating raw sound waves all at once, it breaks the task into 4 stages: Plan -> Rough Draft -> Acoustic Detail -> Waveform.",
    "The model has about 3 to 4 billion parameters and runs on a standard 24 GB GPU.",
    "The weights are released under CC BY-NC 4.0 for non-commercial study and experimentation."
  ],
  quiz: [
    {
      id: "q0_1",
      question: "Why does YuE2 break music generation into multiple stages rather than generating sound waves directly?",
      options: [
        "Because Python scripts can only execute four lines of code at once",
        "Because one second of stereo audio contains 96,000 numbers; working in stages manages this complexity",
        "Because the model needs to wait for human approval after every single note",
        "Because the GPU can only process lyrics in English"
      ],
      correctIndex: 1,
      explanation: "Audio is enormously data-dense (96,000 numbers every second). By planning the score first, then building a rough draft, then refining the acoustic texture, YuE2 manages this complexity step by step."
    },
    {
      id: "q0_2",
      question: "What is an AI 'parameter' in plain terms?",
      options: [
        "A user prompt typed into the terminal",
        "An adjustable number (weight) inside the model that controls how signals flow",
        "The file format of the generated audio track",
        "The license agreement governing copyright"
      ],
      correctIndex: 1,
      explanation: "A parameter (or weight) is an internal adjustable number inside the neural network. YuE2 has around 3 to 4 billion of these tiny numbers learned during training."
    },
    {
      id: "q0_3",
      question: "Under what license are the YuE2-3B weights released by M-A-P?",
      options: [
        "Public Domain (CC0) with zero restrictions",
        "Closed proprietary source with monthly subscription fee",
        "CC BY-NC 4.0 (free for non-commercial use with attribution)",
        "GPL v3 copyleft requiring all generated songs to be open-source"
      ],
      correctIndex: 2,
      explanation: "YuE2 is shared under the Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)."
    }
  ]
};

export const ch01_generative: Chapter = {
  id: 1,
  slug: "what-generative-means",
  title: "What 'Generative' Means",
  subtitle: "The machine that learns what usually comes next",
  pipelineStage: "foundations",
  estMinutes: 6,
  hook: "How does a computer 'create' something brand new if it's only following arithmetic equations?",
  analogy: {
    title: "The Improv Guitarist Who Heard Every Song",
    body: "Picture an experienced studio session guitarist who has listened to ten million songs. If you play four bars of a blues progression, she immediately knows forty different riffs that would sound natural next. She doesn't have a rigid script; she picks a riff that fits the groove, taking a slight creative variation each time.",
    breaksDown: "The human musician feels emotion, understands the bittersweet heartbreak of the blues, and chooses notes with personal aesthetic taste. The generative model has zero feelings or musical taste—it has a statistical probability table derived from billions of text and audio fragments."
  },
  concept: [
    {
      heading: "Discriminative vs. Generative",
      content: "Traditional machine learning is discriminative: give it an audio clip, and it answers a multiple-choice question ('Is this jazz or rock?'). Generative AI does the reverse: give it a prompt, and it produces a brand-new audio file that matches that style.",
      eli5Content: "Discriminative AI is like a teacher grading a test ('That's a cat!'). Generative AI is like an artist painting a new cat from scratch."
    },
    {
      heading: "Next-Token Prediction: The Core Engine",
      content: "Under the hood, almost every modern generative model does one simple thing: given a sequence of things that came before, calculate a probability distribution over what could possibly come next, then pick one. Repeat this millions of times, and a full song emerges.",
      eli5Content: "The model just guesses the best next piece over and over, like your phone guessing the next word when you text."
    },
    {
      heading: "Statistics, Not Magic",
      content: "When YuE2 generates a soaring vocal harmony, it didn't plan it out of inspiration. It calculated that in thousands of training examples with high emotional intensity, a major third harmony usually follows that exact melody leap.",
      eli5Content: "The computer doesn't know what music feels like—it just knows which sounds usually follow other sounds!"
    }
  ],
  inYuE2: {
    summary: "YuE2's autoregressive backbone uses next-token prediction to write both the ABC sheet music score and the semantic audio tokens.",
    factIds: ["architecture_claim", "two_stages_audio"]
  },
  pythonCorner: [
    {
      title: "A 10-Line Generative Predictor in Pure Python",
      language: "python",
      type: "runnable",
      description: "This runnable pure-Python script builds a tiny bigram word predictor using Python's standard collections and random modules.",
      code: `import collections
import random

# A tiny training corpus of musical lyrics
corpus = "sunlight morning pass sunlight kitchen glass morning pass sunlight".split()

# Learn transitions: word -> list of words that followed it
transitions = collections.defaultdict(list)
for current_word, next_word in zip(corpus[:-1], corpus[1:]):
    transitions[current_word].append(next_word)

# Generate 5 words by predicting what comes next
current = "sunlight"
generated = [current]
for _ in range(4):
    options = transitions[current]
    current = random.choice(options)
    generated.append(current)

print("Generated phrase:", " ".join(generated))`
    }
  ],
  newTerms: ["probability-distribution"],
  recap: [
    "Discriminative AI categorizes existing data; Generative AI creates new data.",
    "The core mechanism of generative AI is predicting what comes next based on past patterns.",
    "The model outputs a probability distribution (percentage chance for each option), not a single rigid answer.",
    "Music AI works by applying this next-item prediction to musical symbols and audio tokens."
  ],
  quiz: [
    {
      id: "q1_1",
      question: "What is the primary difference between discriminative AI and generative AI?",
      options: [
        "Discriminative AI runs on GPUs, while Generative AI runs on CPUs",
        "Discriminative AI classifies or labels input; Generative AI produces new content",
        "Generative AI only works on text, while discriminative AI works on audio",
        "Discriminative AI never uses probabilities"
      ],
      correctIndex: 1,
      explanation: "Discriminative models classify or predict labels (e.g. 'Is this rock?'), whereas generative models synthesize new data matching learned patterns."
    },
    {
      id: "q1_2",
      question: "What does an AI's 'probability distribution' represent?",
      options: [
        "A list of all possible next choices, each with a percentage probability summing to 100%",
        "The speed at which the GPU downloads weights",
        "The volume level of the left stereo channel",
        "A hardcoded Python tuple that cannot change"
      ],
      correctIndex: 0,
      explanation: "A probability distribution assigns a probability to every possible candidate outcome, ensuring all probabilities sum to 1.0 (or 100%)."
    },
    {
      id: "q1_3",
      question: "Where does the analogy of an 'experienced improv musician' break down for an AI model?",
      options: [
        "The model cannot produce sound waves",
        "The model has no feelings, consciousness, or artistic intent—it operates strictly on statistics",
        "The model runs faster than human ear perception",
        "The model requires 240 volts of electricity"
      ],
      correctIndex: 1,
      explanation: "While an improv musician chooses notes with human feeling and taste, a neural network operates purely on statistical calculations over mathematical representations."
    }
  ]
};

export const ch02_tokens: Chapter = {
  id: 2,
  slug: "tokens-numbered-lego-bricks",
  title: "Tokens: Numbered LEGO Bricks",
  subtitle: "Turning words and music into integer sequences",
  pipelineStage: "foundations",
  estMinutes: 6,
  hook: "Computers cannot read letters or hear sound waves directly. How do we turn 'Sunlight' into numbers a computer can manipulate?",
  analogy: {
    title: "The LEGO Kit Catalog",
    body: "Think of an architectural LEGO kit with 150,000 distinct bricks. Every brick design—a blue 2x4 block, a curved red arch, a tiny clear window—has a unique SKU number in the manual. When you write instructions to build a house, you don't write poetic descriptions of plastic; you write a sequence of numbers: [7104, 302, 8819].",
    breaksDown: "Real LEGO bricks have physical shape, weight, and friction. Tokens are pure abstract integers with zero inherent meaning until the model maps them to coordinates in the next step."
  },
  concept: [
    {
      heading: "Why Not Whole Words or Single Letters?",
      content: "Single letters (a, b, c) are too small: the word 'extraordinary' would take 13 steps to process. Whole words are too rigid: English has hundreds of thousands of words, and slang or typos would be completely unknown. Sub-word tokenization finds the sweet spot: common words are single tokens, while rare words are split into known pieces.",
      eli5Content: "Instead of learning every single English word, the AI learns common word pieces—like 'play' and 'ing'—which can build almost any word like puzzle pieces."
    },
    {
      heading: "The Vocabulary: A Python Dictionary",
      content: "A tokenizer is powered by a fixed vocabulary: a Python dictionary mapping text strings to unique integers. For example: `{'Sun': 3821, 'light': 410, ' through': 958}`. Once created, the vocabulary never changes during model execution.",
      eli5Content: "The vocabulary is just a giant dictionary where every piece of text has a permanent ID number, like phone numbers in an address book."
    },
    {
      heading: "YuE2's Tokenizer: Qwen tiktoken",
      content: "YuE2 uses a Byte-Pair Encoding (BPE) tokenizer stored in `qwen.tiktoken`. It handles English, Chinese, punctuation, whitespace, and special control tokens like `<|im_start|>` and `<|endoftext|>`. Even music notation (ABC text) is tokenized with these same sub-word pieces!",
      eli5Content: "YuE2 uses a popular open-source tokenizer that knows both English and Chinese words, plus musical notes written in letters."
    }
  ],
  inYuE2: {
    summary: "YuE2 ships with qwen.tiktoken in its repository, which converts prompt text, lyrics, and ABC notation into discrete integer sequences.",
    factIds: ["tokenizer", "symbolic_planning"]
  },
  pythonCorner: [
    {
      title: "Building a Toy Sub-Word Tokenizer in Python",
      language: "python",
      type: "runnable",
      description: "A pure-Python demonstration of how a vocabulary lookup table encodes text into integer IDs and decodes them back.",
      code: `# A tiny vocabulary lookup table (dict[str, int])
VOCAB = {
    "<pad>": 0, "Sun": 1, "light": 2, "through": 3,
    "the": 4, "glass": 5, "pass": 6, " ": 7, "\\n": 8
}
REVERSE_VOCAB = {idx: token for token, idx in VOCAB.items()}

def encode(text: str) -> list[int]:
    tokens = []
    i = 0
    while i < len(text):
        matched = False
        # Greedy matching against known tokens
        for size in (7, 5, 4, 3, 2, 1):
            chunk = text[i:i + size]
            if chunk in VOCAB:
                tokens.append(VOCAB[chunk])
                i += len(chunk)
                matched = True
                break
        if not matched:
            i += 1  # Skip unknown character
    return tokens

def decode(token_ids: list[int]) -> str:
    return "".join(REVERSE_VOCAB.get(idx, "?") for idx in token_ids)

encoded = encode("Sunlight through the glass")
print("Token IDs:", encoded)
print("Decoded back:", decode(encoded))`
    }
  ],
  newTerms: ["token", "tokenizer", "vocabulary"],
  recap: [
    "A token is an integer representing a word piece, character, musical symbol, or audio code.",
    "A tokenizer converts human text into a list of integer token IDs using a fixed vocabulary dictionary.",
    "Sub-word tokenization allows models to handle common words efficiently while decomposing unfamiliar words.",
    "YuE2 uses the Qwen-style tiktoken tokenizer to tokenize both lyric text and ABC sheet music notation."
  ],
  quiz: [
    {
      id: "q2_1",
      question: "Why do modern AI models use sub-word tokens instead of whole-word vocabularies?",
      options: [
        "Because GPUs can only store single-digit numbers",
        "To balance vocabulary size with flexibility, allowing rare words to be built from familiar pieces",
        "Because sub-words consume zero bytes of memory",
        "To prevent users from typing in lower-case letters"
      ],
      correctIndex: 1,
      explanation: "Sub-word tokenization prevents the vocabulary from blowing up to millions of words while ensuring rare words or typos can still be represented as pieces."
    },
    {
      id: "q2_2",
      question: "In Python terms, what is a model's 'vocabulary'?",
      options: [
        "A list of audio sound wave amplitudes",
        "A dictionary mapping string tokens to unique integer IDs",
        "A random number generator with a seed",
        "The license file in the GitHub repository"
      ],
      correctIndex: 1,
      explanation: "A vocabulary is fundamentally a `dict[str, int]` mapping every recognized token string to a unique integer ID."
    },
    {
      id: "q2_3",
      question: "Which tokenizer file is included in YuE2-3B's repository?",
      options: [
        "llama.tiktoken",
        "bert_vocab.txt",
        "qwen.tiktoken",
        "gpt2.json"
      ],
      correctIndex: 2,
      explanation: "As documented in YuE2-3B's official repository, it uses `qwen.tiktoken`."
    }
  ]
};

export const ch03_embeddings: Chapter = {
  id: 3,
  slug: "embeddings-coordinates-on-a-map",
  title: "Embeddings: Coordinates on a Map",
  subtitle: "Giving every token meaning through multi-dimensional geometry",
  pipelineStage: "foundations",
  estMinutes: 7,
  hook: "To a computer, token ID 42 and token ID 43 are just numbers. How does the model know that 'chorus' and 'verse' belong together, but 'refrigerator' doesn't?",
  analogy: {
    title: "The Neighborhood Map of Concepts",
    body: "Imagine a huge city map. Cafés cluster near bakeries in the market district; bookstores cluster near libraries in the university district; warehouses sit miles away in the industrial zone. If you know an establishment's GPS latitude and longitude, you instantly know what other places it is close to. An embedding is simply GPS coordinates for a word or musical symbol.",
    breaksDown: "A physical city map has 2 dimensions (latitude and longitude). Real AI embeddings have 2,048 or 4,096 dimensions! You cannot visualize 4,000 axes with human eyes, but the mathematical distance formula works exactly the same way as on a flat 2D map."
  },
  concept: [
    {
      heading: "From ID Numbers to Coordinate Vectors",
      content: "An integer ID like 1083 has no concept of meaning: 1084 isn't necessarily related to 1083. An embedding replaces that single number with a vector: a list of thousands of floating-point coordinates, like `[-0.12, 0.84, 0.05, ...]`. Tokens that play similar musical or grammatical roles are given coordinates that sit close to each other.",
      eli5Content: "Instead of just giving each word a badge number, we give it coordinates on a giant map. Words with similar meanings live on the same street!"
    },
    {
      heading: "Measuring Similarity with Distance",
      content: "Because embeddings are lists of numbers, we can measure how similar two tokens are using basic geometry: Euclidean distance (`math.dist`) or cosine similarity (the angle between vectors). If the distance between 'acoustic' and 'guitar' is small, the model considers them related.",
      eli5Content: "We can measure how close two words are just by checking the straight-line distance between their points on the map."
    },
    {
      heading: "Learned, Not Hand-Coded",
      content: "Nobody sat down and typed coordinates for millions of tokens. The embedding coordinates start as pure random numbers. During training, every time the model adjusts its weights, the embedding vectors nudge closer to concepts they appear with, and push away from concepts they don't.",
      eli5Content: "The computer moved the words around on the map by itself during training until related words ended up close together."
    }
  ],
  inYuE2: {
    summary: "YuE2 transforms input token IDs for lyrics, style tags, and ABC notes into high-dimensional embedding vectors before feeding them into the transformer layers.",
    factIds: ["architecture_claim", "parameter_count"]
  },
  pythonCorner: [
    {
      title: "Measuring Vector Distance in Pure Python",
      language: "python",
      type: "runnable",
      description: "This runnable snippet shows how embedding coordinates are looked up and compared using Python's standard math library.",
      code: `import math

# Toy 2D embeddings for musical terms (real models use 2048+ dimensions)
EMBEDDINGS = {
    "guitar":  [0.85, 0.80],
    "acoustic": [0.82, 0.78],
    "drums":   [0.70, 0.20],
    "lyrics":  [0.15, 0.85],
    "verse":   [0.20, 0.90],
}

def nearest_neighbor(target_word: str):
    target_vec = EMBEDDINGS[target_word]
    distances = {}
    for word, vec in EMBEDDINGS.items():
        if word != target_word:
            distances[word] = round(math.dist(target_vec, vec), 3)
    return sorted(distances.items(), key=lambda item: item[1])

print("Closest to 'guitar':", nearest_neighbor("guitar"))
print("Closest to 'verse':", nearest_neighbor("verse"))`
    }
  ],
  newTerms: ["embedding", "vector", "dimension", "similarity"],
  recap: [
    "An embedding is a list of numbers (a vector) representing a token's position in a multi-dimensional space.",
    "Tokens with related musical or semantic meanings end up with coordinates close to each other.",
    "Similarity is measured using mathematical distance formulas like Euclidean distance.",
    "Embeddings are learned automatically during training by nudging coordinates when predictions succeed or fail."
  ],
  quiz: [
    {
      id: "q3_1",
      question: "Why do models convert integer token IDs into embedding vectors?",
      options: [
        "Because integer IDs have no geometric meaning, whereas vector coordinates capture semantic similarity",
        "To compress the file size on the hard drive",
        "Because integer IDs cannot be saved in Python files",
        "To encrypt the lyrics against unauthorized reading"
      ],
      correctIndex: 0,
      explanation: "Integer IDs are just arbitrary catalog indices. Embedding vectors place tokens in a continuous coordinate space where distance reflects relationship."
    },
    {
      id: "q3_2",
      question: "If two tokens have a very small Euclidean distance between their embedding vectors, what does that imply?",
      options: [
        "The model crashed during inference",
        "The two tokens appear in similar contexts and share related roles in the training data",
        "They have identical character counts in English",
        "They both start with the letter A"
      ],
      correctIndex: 1,
      explanation: "A small distance in embedding space indicates the model learned that these tokens appear in similar linguistic or musical contexts."
    },
    {
      id: "q3_3",
      question: "How many dimensions do real production models like YuE2 use for their embeddings?",
      options: [
        "Exactly 2 (X and Y coordinates)",
        "Thousands of dimensions (e.g., 2,048 or 4,096)",
        "Zero dimensions",
        "Exactly 16, matching MIDI channels"
      ],
      correctIndex: 1,
      explanation: "While toy demos use 2D coordinates so we can draw them on a screen, real foundation models use thousands of dimensions per token."
    }
  ]
};
