import React, { useState } from "react";
import { Chapter } from "../../content/types";
import { YUE2_FACTS } from "../../content/facts";
import { AnalogyBox } from "../common/AnalogyBox";
import { PythonCorner } from "../common/PythonCorner";
import { Quiz } from "../common/Quiz";
import { AudioPlayer } from "../common/AudioPlayer";
import { Term } from "../common/Term";

// Interactive Demos
import { Ch01_ContinuePhrase } from "../demos/Ch01_ContinuePhrase";
import { Ch02_TokenizerDemo } from "../demos/Ch02_TokenizerDemo";
import { Ch03_EmbeddingExplorer } from "../demos/Ch03_EmbeddingExplorer";
import { Ch04_AttentionHeatmap } from "../demos/Ch04_AttentionHeatmap";
import { Ch05_SamplingDice } from "../demos/Ch05_SamplingDice";
import { Ch06_GradientDescent } from "../demos/Ch06_GradientDescent";
import { Ch07_NumberCounter } from "../demos/Ch07_NumberCounter";
import { Ch08_AbcStudio } from "../demos/Ch08_AbcStudio";
import { Ch09_SemanticTimeline } from "../demos/Ch09_SemanticTimeline";
import { Ch10_FlowMatchingDemo } from "../demos/Ch10_FlowMatchingDemo";
import { Ch11_VaeCompression } from "../demos/Ch11_VaeCompression";
import { Ch12_BrainLayout } from "../demos/Ch12_BrainLayout";
import { Ch13_WalkthroughStepper } from "../demos/Ch13_WalkthroughStepper";
import { Ch14_SteeringSandbox } from "../demos/Ch14_SteeringSandbox";
import { Ch15_PhonemeAndEthics } from "../demos/Ch15_PhonemeAndEthics";

import {
  HelpCircle,
  Clock,
  Sparkles,
  ArrowRight,
  ArrowLeft,
  CheckCircle,
  Lightbulb,
  ExternalLink
} from "lucide-react";

interface ChapterViewProps {
  chapter: Chapter;
  onNavigateChapter: (chapterId: number) => void;
  onNavigateToGlossary: (termId?: string) => void;
  isFirst: boolean;
  isLast: boolean;
}

export const ChapterView: React.FC<ChapterViewProps> = ({
  chapter,
  onNavigateChapter,
  onNavigateToGlossary,
  isFirst,
  isLast
}) => {
  // Toggle for "Explain it simpler" (ELI5) for each section (§4.4)
  const [eli5Mode, setEli5Mode] = useState<Record<number, boolean>>({});

  const toggleEli5 = (secIdx: number) => {
    setEli5Mode((prev) => ({ ...prev, [secIdx]: !prev[secIdx] }));
  };

  // Render the dedicated interactive demo per chapter
  const renderInteractiveDemo = () => {
    switch (chapter.id) {
      case 0:
        return (
          <div className="space-y-4 my-8">
            <h4 className="text-sm font-semibold text-slate-900 dark:text-slate-100 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-cyan-600" />
              Listen: Authentic Songs Generated by YuE2-3B
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <AudioPlayer
                src="/audio/tonight-awake.mp3"
                title="Tonight Awake (Pop Rock)"
                genreTag="Full Band + Vocals"
                caption="Notice how the lead vocals, vocal harmonies, and distorted rhythm guitar all blend in clean 48 kHz stereo."
              />
              <AudioPlayer
                src="/audio/cyber-metal.mp3"
                title="Cyber Metal"
                genreTag="Heavy Metal Riff"
                caption="Listen for the intense drum transients, screaming electric guitars, and aggressive male vocals."
              />
            </div>
          </div>
        );
      case 1:
        return <Ch01_ContinuePhrase />;
      case 2:
        return <Ch02_TokenizerDemo />;
      case 3:
        return <Ch03_EmbeddingExplorer />;
      case 4:
        return <Ch04_AttentionHeatmap />;
      case 5:
        return <Ch05_SamplingDice />;
      case 6:
        return <Ch06_GradientDescent />;
      case 7:
        return <Ch07_NumberCounter />;
      case 8:
        return <Ch08_AbcStudio />;
      case 9:
        return <Ch09_SemanticTimeline />;
      case 10:
        return <Ch10_FlowMatchingDemo />;
      case 11:
        return <Ch11_VaeCompression />;
      case 12:
        return <Ch12_BrainLayout />;
      case 13:
        return <Ch13_WalkthroughStepper />;
      case 14:
        return <Ch14_SteeringSandbox />;
      case 15:
        return <Ch15_PhonemeAndEthics />;
      default:
        return null;
    }
  };

  return (
    <article className="max-w-3xl mx-auto py-8 px-4 sm:px-6 space-y-10">
      {/* Chapter Header */}
      <header className="space-y-3 border-b border-slate-200 dark:border-slate-800 pb-6">
        <div className="flex items-center gap-2 text-xs text-slate-500">
          <span className="font-semibold text-cyan-600 dark:text-cyan-400 uppercase tracking-wider">
            Chapter {chapter.id}
          </span>
          <span aria-hidden="true">·</span>
          <span className="flex items-center gap-1">
            <Clock className="w-3.5 h-3.5 text-slate-400" />
            {chapter.estMinutes} min read
          </span>
          <span aria-hidden="true">·</span>
          <span>Stage: {chapter.pipelineStage}</span>
        </div>

        <h1 className="text-2xl sm:text-4xl font-bold tracking-tight text-slate-900 dark:text-slate-100 text-balance">
          {chapter.title}
        </h1>

        <p className="text-base text-slate-600 dark:text-slate-400">
          {chapter.subtitle}
        </p>

        {/* Hook */}
        <div className="p-4 rounded-xl bg-cyan-50/70 dark:bg-cyan-950/40 border border-cyan-200/80 dark:border-cyan-800/60 text-xs sm:text-sm text-cyan-950 dark:text-cyan-200 font-medium flex items-start gap-3">
          <HelpCircle className="w-4 h-4 text-cyan-600 dark:text-cyan-400 shrink-0 mt-0.5" />
          <p>{chapter.hook}</p>
        </div>
      </header>

      {/* 1. Analogy First (Golden Rule G2) */}
      <AnalogyBox
        title={chapter.analogy.title}
        body={chapter.analogy.body}
        breaksDown={chapter.analogy.breaksDown}
      />

      {/* 2. Concept Sections with ELI5 Toggles */}
      <section aria-label="Core Concept Sections" className="space-y-8">
        {chapter.concept.map((sec, idx) => {
          const isEli5 = eli5Mode[idx] || false;
          return (
            <div
              key={idx}
              className="space-y-2.5 p-5 rounded-2xl border border-slate-100 dark:border-slate-800/80 bg-white dark:bg-slate-900/40 shadow-2xs"
            >
              <div className="flex items-center justify-between gap-2">
                <h3 className="text-base sm:text-lg font-bold text-slate-900 dark:text-slate-100">
                  {sec.heading}
                </h3>

                {sec.eli5Content && (
                  <button
                    type="button"
                    onClick={() => toggleEli5(idx)}
                    className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-medium transition-colors ${
                      isEli5
                        ? "bg-amber-100 dark:bg-amber-950 text-amber-900 dark:text-amber-200 border border-amber-300 dark:border-amber-800 font-semibold"
                        : "bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200"
                    }`}
                  >
                    <Lightbulb className="w-3.5 h-3.5 text-amber-500" />
                    <span>{isEli5 ? "Standard View" : "Explain Simpler (ELI5)"}</span>
                  </button>
                )}
              </div>

              {isEli5 && sec.eli5Content ? (
                <div className="p-4 rounded-xl bg-amber-50/70 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800/60 text-xs sm:text-sm text-amber-950 dark:text-amber-200 leading-relaxed italic">
                  <strong>Simpler Explanation: </strong>
                  {sec.eli5Content}
                </div>
              ) : (
                <p className="text-sm sm:text-base text-slate-700 dark:text-slate-300 leading-relaxed whitespace-pre-line font-normal">
                  {sec.content}
                </p>
              )}
            </div>
          );
        })}
      </section>

      {/* 3. Primary Interactive Demonstration */}
      <section aria-label="Interactive Demonstration" className="my-8">
        {renderInteractiveDemo()}
      </section>

      {/* 4. Where this shows up in YuE2 (Facts Register) */}
      <section aria-label="YuE2 Architecture Anchoring" className="my-8 p-5 rounded-2xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 space-y-3">
        <span className="text-xs font-mono uppercase tracking-wider text-cyan-600 dark:text-cyan-400 font-semibold block">
          Where This Shows Up in YuE2-3B
        </span>
        <p className="text-xs sm:text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
          {chapter.inYuE2.summary}
        </p>

        {chapter.inYuE2.factIds.length > 0 && (
          <div className="pt-2 border-t border-slate-200 dark:border-slate-800 space-y-2">
            <span className="text-[11px] font-semibold text-slate-500 block">
              Verified Technical Facts (arXiv:2609.33757 & Model Card):
            </span>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
              {chapter.inYuE2.factIds.map((fid) => {
                const fact = YUE2_FACTS[fid];
                if (!fact) return null;
                return (
                  <div
                    key={fid}
                    className="p-2.5 rounded-lg bg-white dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700/80"
                  >
                    <strong className="block text-slate-900 dark:text-slate-100 font-medium">
                      {fact.name}
                    </strong>
                    <span className="text-slate-600 dark:text-slate-300 text-[11px] block mt-0.5">
                      {fact.detail}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </section>

      {/* 5. Python Corner */}
      <PythonCorner blocks={chapter.pythonCorner} />

      {/* New Terms Introduced */}
      {chapter.newTerms.length > 0 && (
        <section aria-label="New terms introduced" className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/50 text-xs flex flex-wrap items-center gap-2">
          <span className="text-slate-500 font-medium">Terms introduced:</span>
          {chapter.newTerms.map((tId) => (
            <Term key={tId} id={tId} onNavigateToGlossary={onNavigateToGlossary} />
          ))}
        </section>
      )}

      {/* 6. Chapter Recap */}
      <section aria-label="Chapter Recap" className="p-5 rounded-2xl bg-cyan-50/40 dark:bg-cyan-950/20 border border-cyan-100 dark:border-cyan-900/40 space-y-3">
        <h4 className="font-bold text-sm text-cyan-950 dark:text-cyan-200 flex items-center gap-2">
          <CheckCircle className="w-4 h-4 text-cyan-600" />
          Chapter Recap
        </h4>
        <ul className="space-y-1.5 text-xs sm:text-sm text-slate-700 dark:text-slate-300">
          {chapter.recap.map((bullet, idx) => (
            <li key={idx} className="flex items-start gap-2">
              <span className="text-cyan-600 font-bold shrink-0">·</span>
              <span>{bullet}</span>
            </li>
          ))}
        </ul>
      </section>

      {/* 7. Chapter Quiz (Golden Rule G7) */}
      <Quiz
        chapterId={chapter.id}
        questions={chapter.quiz}
      />

      {/* Navigation Footer */}
      <footer className="pt-6 border-t border-slate-200 dark:border-slate-800 flex items-center justify-between gap-4">
        {!isFirst ? (
          <button
            type="button"
            onClick={() => onNavigateChapter(chapter.id - 1)}
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 text-xs sm:text-sm font-medium text-slate-700 dark:text-slate-300 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Chapter {chapter.id - 1}</span>
          </button>
        ) : (
          <div />
        )}

        {!isLast ? (
          <button
            type="button"
            onClick={() => onNavigateChapter(chapter.id + 1)}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-white text-xs sm:text-sm font-medium shadow-md transition-all active:scale-95 cursor-pointer"
          >
            <span>Next: Chapter {chapter.id + 1}</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        ) : (
          <button
            type="button"
            onClick={() => onNavigateToGlossary()}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-white text-xs sm:text-sm font-medium shadow-md transition-all active:scale-95"
          >
            <span>Finish to Glossary & Cheat Sheet</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        )}
      </footer>
    </article>
  );
};
